### ISSUE TITLE
Not setting ENV vars on Lambda, v1.1.2 

### ISSUE THREAD

**Issue by slavivanov** [neverendingqs/serverless-dotenv-plugin#11]
This plugin would read the env file but the env variables would not be set on the AWS lambda function. Maybe it was conflicting with other plugins. 
I managed to fix it by adding the hook:
```"before:package:initialize": this.loadEnv.bind(this)```
to `this.hooks` in the constructor in index.js.

Maybe this would help anyone. 
I'm not convinced this is an universal solution as to create a pull request.

**Comment by todda00** [comment]
I ran into this as well. adding before:package:initialize as listed above fixed it for me
