### ISSUE TITLE
[QUESTION] Serverless Hooks

### ISSUE THREAD

**Issue by CDimonaco** [neverendingqs/serverless-dotenv-plugin#14]
Hi,
What's the reason behind the hooks on serverless stages?
If I need the env variables in other hooks rather than the hardcoded in the plugin class, what's the point to have hooks hardcoded?

Why not just to load the env variables regardless of the current serverless stage?

Thanks in advance,

**Comment by colynb** [comment]
You're absolutely right. Makes no sense.  I'll be removing the hooks in an upcoming fix here in a few minutes.
