### ISSUE TITLE
[FEATURE REQUEST] additional option - exclude

### ISSUE THREAD

**Issue by shierro** [neverendingqs/serverless-dotenv-plugin#15]
Hi here,

Thanks for creating this awesome plugin mate! Helped me a lot :)

I would like to know your thoughts regarding adding an additional option - **exclude**
It's helpful in my case since i just want to blacklist a list of ENVs that I don't want to use & push

**Comment by colynb** [comment]
This is a great idea... basically, support for both a whitelist and a blacklist. Let me think some more about it.

**Comment by shierro** [comment]
cool! thanks for considering it. let me know how you go :)

**Comment by colynb** [comment]
Just pushed an `exclude` option to this plugin
