### ISSUE TITLE
Cannot have parameterized `stage` and `region`

### ISSUE THREAD

**Issue by jsstrn** [neverendingqs/serverless-dotenv-plugin#157]
Parameterized `stage` and `region` is no longer allowed. They must be in plain text. 

Follow these steps to reproduce deprecation warning: 
- Set `lambdaHashingVersion` to `20201221` in `serverless.yml`.
- Set `stage` or `region` in `serverless.yml` to use an environment variable (e.g. `${env:STAGE}`). 
- Run `sls deploy`

Perhaps we should update the [example usage](https://github.com/neverendingqs/serverless-dotenv-plugin/tree/master/examples/simple-express-app).

Source: [Parameterized org, app, service, stage, and region usage](https://www.serverless.com/framework/docs/deprecations#parameterized-org-app-service-stage-and-region-usage)

**Comment by neverendingqs** [comment]
Sorry been really busy.

If I'm understanding correctly, this just requires an update to the example usage, and no code changes. Is that correct?
