### ISSUE TITLE
Can't read multi line env variable - v2.62.0

### ISSUE THREAD

**Issue by liadperetz** [neverendingqs/serverless-dotenv-plugin#172]
I'm trying to load an enviroment variable which is value is a multi-line string and use it inside an AWS lambda:
ENV_VAR ="first line
...
...
...
last line"

For some reason, it loads only the first line.

**Comment by neverendingqs** [comment]
Looking at the [Node dotenv docs](https://github.com/motdotla/dotenv#rules), it looks like you need to use `\n` to indicate newlines.

Note: this may differ between languages (e.g. [Ruby's dotenv supports using line breaks within double-quotes](https://github.com/bkeepers/dotenv#multi-line-values))
