### ISSUE TITLE
Just to say thanks

### ISSUE THREAD

**Issue by shalvah** [neverendingqs/serverless-dotenv-plugin#18]
Just want to say, great work with this. Was thinking I would have to implement it myself, till I stumbled on this. I'm also willing to volunteer as a maintainer if you ever need help.

Also, what do you think of getting this into the core framework? It's a terribly useful feature because for anyone using version control, managing secrets is hell (copy them out from your `serverless.yml` before you commit).

**Comment by colynb** [comment]
I'm sorry I never said, you're welcome. :-D I'm going through and cleaning up issues finally and I just now noticed this. But you're right, when I created this I was very surprised it wasn't part of the core framework. I thought eventually they would get to it but I'm not seeing any conversations around it.

Cheers!
