### ISSUE TITLE
Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by hsz** [neverendingqs/serverless-dotenv-plugin#2]
There is an error

      Cannot read property 'path' of undefined

if no custom configuration for `dotenv` is provided. It was fixed with 3391b242ea56876bf4b6f39ed87c06274ff95e8d

Can you please relese this fix to npm?

**Comment by sbstjn** [comment]
Would be awesome to have this fixed on NPM 👍

**Comment by colynb** [comment]
Just pushed to npm.
