### ISSUE TITLE
Not loading env file from stage param

### ISSUE THREAD

**Issue by alexcroox** [neverendingqs/serverless-dotenv-plugin#201]
` "api:dev": "nodemon --exec 'serverless offline start --stage local-dev --httpPort 3001' -e 'js'",`

`npm run api:dev`

```
[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js
[nodemon] starting `serverless offline start --stage local-dev --httpPort 3001`
DOTENV: Loading environment variables from .env.development:
	 - [...]

Starting Offline at stage local-dev (eu-west-2)
```

**Why does it load environment variables from `.env.development` and not `.env.local-dev`?**

serverless.yml
```
service: test-api
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-optimize
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  memorySize: 128
  timeout: 15

custom:
  optimize:
    debug: false
    minify: false
    includePaths: ['package.json', 'locales/', 'api/email-templates/']
  prune:
    automatic: true
    number: 3

functions:
  app:
    handler: api/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
```

**Comment by neverendingqs** [comment]
Any chance you have an environment variable named `NODE_ENV` set to `development`? If so, that takes precedence when resolving which dotenv file to use over `--stage`.

**Comment by neverendingqs** [comment]
If so, there is a feature request to change that behaviour: https://github.com/neverendingqs/serverless-dotenv-plugin/issues/150

**Comment by alexcroox** [comment]
I'm not specifying it but probably my machine default.

Starting with `cross-env NODE_ENV=local-dev serverless offline start --stage local --httpPort 3001` resolves this, but no idea on the impact on other packages that look for NODE_ENV development to work properly. 

I'll keep an eye on the feature request thanks.
