### ISSUE TITLE
basePath not getting resolve

### ISSUE THREAD

**Issue by LiFengK** [neverendingqs/serverless-dotenv-plugin#214]
custom:
  dotenv:
    basePath: ../../

I'm having the config as above but got erroring on resolving variable.

Any helps will be appreciated

**Comment by aserhii87** [comment]
I faced the same issue. Any idea how to fix it?

**Comment by neverendingqs** [comment]
Please include a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) as per https://github.com/neverendingqs/serverless-dotenv-plugin/issues/new?assignees=&labels=bug&template=bug_report.md&title=.
