### ISSUE TITLE
Most recent commit broke variable evaluation.

### ISSUE THREAD

**Issue by naturalethic** [neverendingqs/serverless-dotenv-plugin#22]
This plugin *does* require hooks.

From https://serverless.com/framework/docs/providers/aws/guide/plugins/:

> Note: Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.

**Comment by colynb** [comment]
I appreciate the PR. I'll evaluate it hopefully this week. The issue I was trying to solve that others were having an issue with, is the ability to use env vars in the provider section of the yaml. Other users were trying to use provider details like "stage" to dynamically load the proper env file (e.g. `.env.dev`). I don't think it's logically possible to do both. Is that something you would be able to help with?

**Comment by naturalethic** [comment]
I was trying to do the same thing you mentioned, resolve .etc file location based on stage.

I don't think it's possible to do both.  It would require resolving certain variables first (the stage), then the .etc variables, then all the rest.  I don't think there is any mechanism for this in the architecture.

I think people will just have to settle with a single .etc file and swap them around outside of serverless by some other mechanism.

**Comment by naturalethic** [comment]
You can toss this PR, and close the associated ticket.

**Comment by naturalethic** [comment]
Also I'd remove the file selection mechanism in the custom config and the docs.

**Comment by colynb** [comment]
I didn't notice that in the README. It's removed now. Thanks!

**Comment by colynb** [comment]
@naturalethic I figured out a solution for which I will be adding a fix for shortly. When you run the deploy command `sls deploy` you can provide the stage as an option: `sls deploy --stage dev`. All CLI options get passed into the plugin. I can use that option to dynamically determine the env file name automatically.

**Comment by colynb** [comment]
@naturalethic I've updated the plugin so that it resolves files names based on what `NODE_ENV` is set to, instead of what stage is set to. See https://github.com/infrontlabs/serverless-dotenv-plugin#automatic-env-file-name-resolution

Note, I have not published this to NPM yet. I want to do some more testing but you can pull the latest from master branch to test it out.

**Comment by naturalethic** [comment]
I like the solution.  However, it is unclear by the documentation if `.env` or `.env.development` is the default when NODE_ENV is unset.

**Comment by colynb** [comment]
@naturalethic I updated the README to be more clear.
