### ISSUE TITLE
Allow ability to set default environment name. 

### ISSUE THREAD

**Issue by GregTimmons** [neverendingqs/serverless-dotenv-plugin#233]
**Is your feature request related to a problem? Please describe.**
We have a set of environment names where `dev` or `development` is already a non-local environment so `sls deploy --stage dev` is not really our default environment for testing new code. Typically we have developers work in a stage we've called `offline`  and we have a basic .env file for it. I want to be able to have a `.env.offline`  that is the default `.env` file for our project. 

**Describe the solution you'd like**
Add a option to the dot-env config to set the default environment name: 
```
 this.config = Object.assign(
      {
        exclude: [],
        include: '*',
        logging: true,
        required: {},
        defaultEnvironment: 'development', 
        variableExpansion: true,
        v4BreakingChanges: false,
      },
      (this.serverless.service.custom &&
        this.serverless.service.custom['dotenv']) ||
        {},
    );
```
```
 /**
   * @param {Object} options
   * @returns {string}
   */
  getEnvironment(options) {
    return (
      process.env.NODE_ENV || options.env || options.stage || this.config.defaultEnv
    );
  }
```

**Describe alternatives you've considered**
Rename all my environments so that `.env.development` is the local and `.env.dev` is our dev server, which is fine, but annoying.

**Comment by neverendingqs** [comment]
I hear you but also torn because 

https://github.com/neverendingqs/serverless-dotenv-plugin/blob/5344b15ff29743dc6eb6943f54c1fa7339015939/README.md?plain=1#L82-L90

was decided early on.

Hmmm have you tried `env.development.local`?

https://github.com/neverendingqs/serverless-dotenv-plugin/blob/5344b15ff29743dc6eb6943f54c1fa7339015939/README.md?plain=1#L90
