### ISSUE TITLE
All environment variables get included in Lambda export

### ISSUE THREAD

**Issue by jackprosser** [neverendingqs/serverless-dotenv-plugin#28]
Would be good have an exclude plugin option, allowing you to exclude some environment variables from been used and sent to the end Lambda function.

**Comment by aendra-rininsland** [comment]
This would be helpful for being able to specify a particular keypair in the `.env` file for deployment. At present, this will cause a deployment to fail with:

> Lambda was unable to configure your environment variables because the environment variables you have provided contains reserved keys that are currently not supported for modification. Reserved keys used in this request: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

N.b., using the `include` config option seems to allow this, but that means then adding vars in two places (`.env` and `serverless.yml`).

**Comment by colynb** [comment]
I'm thinking about how to do this using a naming convention on environment variable keys but in a way that is backward compatible. Similar to how Create React App does it.

For instance, 

```
AWS_ACCESS_KEY_ID=abc123
LAMBDA_AUTH0_CLIENT_ID=345tyuy
```

Something like that but I need to give it more thought.
