### ISSUE TITLE
possible bug - environment variable value being cut

### ISSUE THREAD

**Issue by shierro** [neverendingqs/serverless-dotenv-plugin#31]
I have an ENV variable, say  `RANDOM_HASH` in my `.env` file

.env
```
RANDOM_HASH="XXXXX#XXXXX%9^XX$4$FYNHtpPs6uc"
```

and on 
serverless.yml
```
custom:
  dotenv:
    include:
      - RANDOM_HASH
```

when i deploy it, what reaches my lambda function only is `XXXXX#XXXXX%9^XX`
Somehow, it has been cut in the first `$`

same thing is found on the `cloudformation-template-update-stack.json` file
```
        "Environment": {
          "Variables": {
            "RANDOM_HASH": "XXXXX#XXXXX%9^XX"
          }
        }
```

so i suspect that the library somehow accidentally split the content. 
Do you have some work around in mind, so that I can upload the same env variable value?

Thanks in advance!

**Comment by colynb** [comment]
The dollar sign is a reserved character used within dotenv-expand which
allows you to "expand" other vars out. See if there's a way to escape it.

**Comment by shierro** [comment]
yeah i thought so, after checking seeing those `$` on the library but i'm not too sure what it does 🤣  I managed to escape it on my .env file using a single quote, and a forward slash

.env
```
RANDOM_HASH='XXXXX#XXXXX%9^XX\$4\$FYNHtpPs6uc'
```

Thanks for taking time too look into this @colynb

**Comment by jeffski** [comment]
This must have been introduced at some stage in the last year or so as it used to work without escaping. Version 2.1.1 works fine, I just used v2.3.2 today in a new project and got caught out by this issue. Thankfully you can escape the $ symbol in both versions and that will work.

**Comment by triwats** [comment]
Howdy @jeffski - by escaping you mean usage of a `\` or by encapsulation? I'm hitting this too, thanks!

EDIT: Forget this, just escaping normally with a `\` works for me, encapuslation of either `'` or `"` however didn't. This is a bit probematic in my case as I'm using it to concat a path for SSM and a environment together.

**Comment by jeffski** [comment]
Hi @triwats, yes, I'm just using a backslash `\` to secape a `$`, not using any kind of encapsulation around it.

**Comment by tafelnl** [comment]
I think this should really be mentioned in the docs. Not everyone is aware of this, and they might bang their head against the wall while figuring this out ;)
