### ISSUE TITLE
"app" value in Serverless.yml not working

### ISSUE THREAD

**Issue by WilliamBlais** [neverendingqs/serverless-dotenv-plugin#39]
Hello,

I tried using Serverless enterprise with the following configuration;
service: ${env:APP_NAME}
...
app: ${env:SLS_APP_NAME}

However, it seems like ${env:SLS_APP_NAME} isn't being replaced by its value. While I replace it manually, everything works fine.
I can confirm it's not due to the variable not being in the .env, or the wrong environment.

Is this a known bug?

Thanks,
Will

**Comment by anurag-roy** [comment]
I'm getting this:
`"app" and "org" in your serverless config can not use the variable system`

**Comment by neverendingqs** [comment]
Thanks @anurag2pirad, for responding here and on https://github.com/serverless/enterprise-plugin/issues/333!
