### ISSUE TITLE
Fail silently

### ISSUE THREAD

**Issue by benswinburne** [neverendingqs/serverless-dotenv-plugin#4]
Locally I have .dotenv files, but the CI/CD pipelines use real environment variables. As a result each build ends up with this in the log

```
Serverless: DOTENV: Loading environment variables:

 Serverless Plugin Error --------------------------------------

  [serverless-dotenv-plugin] Could not find .env file.
```

It'd be nice if an option could be provided in serverless.yml to fail silently

**Comment by colynb** [comment]
Yeah, you're right and it should be an easy fix. I'll submit a change tomorrow.

**Comment by benswinburne** [comment]
Nice one, thanks very much.

**Comment by tsmith123** [comment]
Was this feature actually added as I'm experiencing the same issues but it has been closed?
