### ISSUE TITLE
Azure support?

### ISSUE THREAD

**Issue by samueledirito** [neverendingqs/serverless-dotenv-plugin#40]
Hello!
I'm trying to migrate from AWS to Azure cloud.
DotEnv plugin is amazing, but I cannot figure it out if I can use it or not :(

Anyone can help?
Thank you very much!

**Comment by colynb** [comment]
I've never used azure before but in theory it should just work. Have you
tried it? Any errors?

**Comment by samueledirito** [comment]
Yes, I tried and what I saw is that Azure needs all env vars in **local.settings.json** file.
If I get it correctly, the plugin is unable to do some kind of copy from .env to it, so I was asking if there's some kind of option that I'm missing.

**Comment by colynb** [comment]
If what you're saying is true, that Azure has specific requirements, then at this time, it's not supported.  Really sorry.

**Comment by jdrydn** [comment]
FYI https://serverless.com/framework/docs/providers/azure/guide/credentials/ - this suggests storing Azure credentials as environment variables, making this plugin extremely useful!
