### ISSUE TITLE
Google / GCP Support?

### ISSUE THREAD

**Issue by joshuaquek** [neverendingqs/serverless-dotenv-plugin#43]
Does this work for GCP? I am using it for AWS Lambdas and it works, but just wondering if it works for other platforms like Google or Azure.

I saw another issue #40 that Azure might not be supported yet.

**Comment by colynb** [comment]
I have never tested this on anything but AWS. I don't believe I am implementing any AWS specific code so, in theory, it should work with any other provider. I'm going to close this issue until more specific issues around this have been raised.
