### ISSUE TITLE
[Feature request] Exclude stages

### ISSUE THREAD

**Issue by bboure** [neverendingqs/serverless-dotenv-plugin#44]
Hi there,

Thanks for this awesome plugin. 

I am in a situation where I'd like to IGNORE completely .env files from some environments. 

My use case is the following:
I am using .env file only in local, when using the offline plugin. 
On "real", deployed environments, env vars are loaded via `middy` through the `ssm` middleware (see [here](https://github.com/middyjs/middy/blob/master/docs/middlewares.md#ssm)).

I am not using ssm in local (offline) mode for many reasons, like: 
- network might not be available
- each dev might need/want a different configuration
- avoids unnecessary calls to ssm API

So, when offline, I am using this plugin to load them directly in `process.env`, and it works great. 

This means that I do not want .env files to be loaded/used in stages other than `local`.

So far, I am working this around by having a `.env.local` file with my custom variables, and an empty default `.env` file for the rest.

When in local, I just do
`sls offline start -s local --env local`.

For the other stages, the empty .env file will just be used and it will just do nothing.

My workaround works.
However, I was wondering it it would make sense to add a new `stages` option in this plugin to select in which stages you want to load the .env file or not. 

A bit like the `include` one, but per stage instead of per variable. 

So, im my use case, I could do:

````
custom:
  dotenv:
    stages:
      - local
````

I am sure that others will also find this useful in some other use cases.
For example, one might not want to deploy to prod using a wrong .env file by mistake. One could easily type the wrong `---env` or `NODE_ENV` values.
Excluding `prod` from the "allowed" stages might then be useful.

WDYT?

BTW, this is inspired by https://github.com/99xt/serverless-dynamodb-local that has this option

**Comment by colynb** [comment]
I like that idea. I haven't had a lot of time to focus on this plugin if it isn't already obvious :-D so if you currently have a work-around that might be good enough for now. To be honest, a lot of change/feature requests that I've received make me nervous. While I do have some tests that would report breaking changes, they're not complete and not fully end-to-end. There's so much more going on in the serverless eco-system that it's likely that any change I make will have a negative impact on the thousands of users who are depending on it. I'm going to close this for now.
