### ISSUE TITLE
Possible conflict with invoke local --env option

### ISSUE THREAD

**Issue by piotr-cz** [neverendingqs/serverless-dotenv-plugin#45]
[AWS - Invoke Local](https://serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/) has an --env option which can be used as

```sh
serverless invoke local --env VAR1=val1 --env VAR2=val2
```

While this plugin [has an option](https://github.com/colynb/serverless-dotenv-plugin#automatic-env-file-name-resolution) to define environment as a fall back to NODE_ENV with the same flag

```sh
serverless invoke local --env production
```

I think there is a conflict but to be honest, I haven't used either of these.

**Comment by AnthonyWC** [comment]
If I am not mistaken, this plugin is only concerned about deployment environment; not runtime environment.  Namely the new command option added is `sls deploy --env <>` for deploy; which doesn't have an `--env` option.

**Comment by teamzz111** [comment]
with sls deploy --env <> doesn't work

**Comment by neverendingqs** [comment]
> If I am not mistaken, this plugin is only concerned about deployment environment; not runtime environment. Namely the new command option added is `sls deploy --env <>` for deploy; which doesn't have an `--env` option.

Thanks! That is correct. The reuse of `--env` is unfortunate as it causes confusion like this.

> with sls deploy --env <> doesn't work

This sounds like another issue. If that is the case, please provide more details in another issue.
