### ISSUE TITLE
Safe to use in production

### ISSUE THREAD

**Issue by codeinaire** [neverendingqs/serverless-dotenv-plugin#46]
Hey, 

Great plugin, easy to use!

I'm just wondering if this is secure to use for production? And if so, what makes it safe to use for production?

Cheers!

**Comment by colynb** [comment]
@codeinaire thanks for the question. I really can't answer that as it's not the plugin's responsibility to ensure its safe use. It really depends on how it's being used and the apps it's being used with. Though there's nothing about this that is inherently unsafe and has one basic simple task: inject env vars into `process.env` from a .env file. After that, the framework, not the plugin handles the rest.
