### ISSUE TITLE
Let users define dotenv plugins?

### ISSUE THREAD

**Issue by vicary** [neverendingqs/serverless-dotenv-plugin#47]
I am porting a project to serverless, where it has a number of dotenv plugins already in place, particularly `dotenv-parse-variables` we use there.

I see that you already added `dotenv-expand` plugin in the source code, do you think it's a good idea to expose an array in `serverless.yml:custom.dotenv.plugins` for users to define their own plugins?

**Comment by colynb** [comment]
What kind of plugins are we talking about? I like the concept.

**Comment by vicary** [comment]
We are using `dotenv-parse-variables` in particular, this is a list of notable dotenv plugins that follow [the recommended way](https://www.npmjs.com/package/dotenv#can-i-customizewrite-plugins-for-dotenv):

1. [dotenv-conversion](https://www.npmjs.com/package/dotenv-conversion)
2. [dotenv-expand](https://www.npmjs.com/package/dotenv-expand)
3. [dotenv-packed](https://www.npmjs.com/package/dotenv-packed)
4. [dotenv-parse-variables](https://www.npmjs.com/package/dotenv-parse-variables)
5. [dotenv-mustache](https://www.npmjs.com/package/dotenv-mustache)

There are many other repo that depends on dotenv but works as a wrapper module, but I don't think they can be easily mixed with one another.

**Comment by colynb** [comment]
Hi @vicary I created a new feature branch that allows you to add any plugin you want. In fact, it's more generic than that. It opens up the possibility of configuring dotenv in many ways. Would you mind doing a code review and testing it out?

The branch is `feature/plugins`

Let me know if you have any questions.

**Comment by vicary** [comment]
Hey this looks very good!

Since it's one step away, I would like to further expose the plugin path as something like`serverless.yml:custom.dotenv.configPath` (let's start a PR to the branch?), but do you think it should share the basePath setting?

**Comment by colynb** [comment]
I created PR #48 a couple of days ago. As is, it assumes that the root of your project is where the config file is but I think using basePath will be good enough.

**Comment by mutantcornholio** [comment]
I would actually like to have ability to disable `dotenv-expand`. 
Unfortunately, that is written separately from `dotenv` and knows nothing about single quotes, because it expects already parsed file.
That way, if you add this to your `.env` file, current version of `serverless-dotenv-plugin` would still try to expand it
```bash
SHOULD_NOT_EXPAND='some$password(with)#chars'
```

**Comment by neverendingqs** [comment]
I will like to close this issue in favour of https://github.com/neverendingqs/serverless-dotenv-plugin/pull/48 and https://github.com/neverendingqs/serverless-dotenv-plugin/issues/90. Please continue the discussion there.

Thanks!
