### ISSUE TITLE
How do you set the options?

### ISSUE THREAD

**Issue by voltuer** [neverendingqs/serverless-dotenv-plugin#49]
README says you can set some options like path, but i don't get how do you add these to the serverless.yaml file

**Comment by callistusasir** [comment]
Create section in your severless.yml file and call this custom, it should be a base level section (0 indent), then user the example from the ReadMe and you should be able to invoke the variables you have set.

```
custom:
  dotenv:
    path:  ./.env
    basePath:  ./
```

place that in you serverless.yml and then you .env should be in the same directory or change the path to where it should be.

Hope that helps
