### ISSUE TITLE
Missing custom property in serverless config causes an error

### ISSUE THREAD

**Issue by benswinburne** [neverendingqs/serverless-dotenv-plugin#5]
SLS_DEBUG=* sls invoke local -f handler -p event.js

Results in no .env loaded and the following error

    Serverless: DOTENV: Loading environment variables:
     Serverless Plugin Error --------------------------------------

      Cannot read property 'dotenv' of undefined

Appears to be caused by

    var config = this.serverless.service.custom['dotenv'];

Because I don't have a `custom` section in my serverless.yml.

Temporary workaround 

    custom:
      dotenv:
        see: https://github.com/infrontlabs/serverless-dotenv-plugin/issues/5

**Comment by colynb** [comment]
Fixed with the pull request
