### ISSUE TITLE
Cannot create property error

### ISSUE THREAD

**Issue by shadrech** [neverendingqs/serverless-dotenv-plugin#53]
Keep getting this error
![Screen Shot 2020-04-02 at 18 52 14](https://user-images.githubusercontent.com/6001129/78282393-1e843d00-7514-11ea-8aa0-0b4f658f2c24.png)
My custom section looks like
```
custom:
  globals: ${file(../../serverless.globals.yml)}
```
with `serverless.globals.yml` also referring to env variables I set in .env (STAGE being one of them)
Serverless successfully deploys the service but not sure how to get rid of this error

**Comment by neverendingqs** [comment]
This looks like symptom of the underlying problem I described for https://github.com/neverendingqs/serverless-dotenv-plugin/issues/38#issuecomment-774552866. Please re-open this issue with a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) if you believe this is a different problem.

Thanks!
