### ISSUE TITLE
Native support for .env in Serverless Framework

### ISSUE THREAD

**Issue by medikoo** [neverendingqs/serverless-dotenv-plugin#63]
@colynb great thanks for this plugin!

We're currently investigating a possibility of supporting `.env` file natively in a Framework.

Main reason is that ideally env vars from `.env` should be loaded at very begin of a process, and resolution via plugin is delayed simply by its nature. So taking into account [dotenv](https://github.com/serverless/serverless/issues/7907) popularity I believe it's a good call to make it a first class citizen in the Framework (it's also already supported in Serverless Components)

Also we simply plan to support it it as convenient env vars transport into `process.env` and nothing more (no automatic leak into lambdas etc.)

We will value your feedback at https://github.com/serverless/serverless/issues/7907

**Comment by colynb** [comment]
Thanks @medikoo - I included my comments in that thread. I'm more than happy to be part of the conversation and will do my best to support your efforts.
