### ISSUE TITLE
URLs ENVs output as [object Object] when using serverless-offline

### ISSUE THREAD

**Issue by skinofstars** [neverendingqs/serverless-dotenv-plugin#69]
When I set a URL in my `.env.developement` file and run using `serverless-offline`, I get the value as `[object Object]`

e.g. 

`ITEMS_TO_PARSE_QUEUE=https://sqs.eu-central-1.amazonaws.com/1234/items-to-parse`

`console.log(process.env.ITEMS_TO_PARSE_QUEUE); // returns [object Object]`

**Comment by neverendingqs** [comment]
Sorry I am not familiar with `serverless-offline`. Could you post a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

You might be running into the same issue as https://github.com/neverendingqs/serverless-dotenv-plugin/issues/38#issuecomment-774552866 maybe?
