### ISSUE TITLE
Create CHANGELOG.md file in project root

### ISSUE THREAD

**Issue by mikelax** [neverendingqs/serverless-dotenv-plugin#78]
# Overview

As a user, I would like to see a CHANGELOG.md file in the project root that is up to date with the current release. 

I see there is a changelog on your private blog, but it is missing the latest version bump (3.1.0), and it would be nicer for the library if that lived inside the project repo. 

## Examples

Here are a couple of changelog file examples, I don't think an automatic changelog generator is necessary, but the format is common and easy to read. 

https://github.com/github-changelog-generator/Github-Changelog-Generator/blob/master/CHANGELOG.md
https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by neverendingqs** [comment]
The amount of details might be too much for me to handle (alone). However, I plan to

* Use `Squash and Commit` when merging every pull request
* Start tagging new releases in Git, which would allow users to do a diff between two different releases

It's not the best developer experience, but I'm hoping it will be enough to understand what has changed between two releases.

Thoughts?

**Comment by mikelax** [comment]
Help, I think your suggestions are a great start and will be a big step up in determining changes between versions. 

Once you have squash commits and are creating versions, you can look to use GitHub actions or even something like semantic release to automatically a changelog. 

The other option is to create the changelog file but only list material updates / changes.

**Comment by neverendingqs** [comment]
I had an idea overnight: if the CHANGELOG is kept up-to-date per pull request, it should be much more manageable. https://github.com/neverendingqs/serverless-dotenv-plugin/pull/102 has more details.
