### ISSUE TITLE
Read issues when value has '$' character

### ISSUE THREAD

**Issue by nishabe** [neverendingqs/serverless-dotenv-plugin#81]
I have observed an issue while reading a value that contains '$' character.
While reading the value using 'process.env', the $ character, as well as the next few characters, are missing.

As an example, consider the below line in .env.local file: 

TEST_1=123$456!@#%^&*()

While reading I see that
process.env.TEST_1 = 123!@#%^&*() // A total of four characters are missing from the original value which are '$456'.

**Comment by neverendingqs** [comment]
The library passes all values to `dotenv-expand`: https://github.com/colynb/serverless-dotenv-plugin/blob/79d8ad4b182bff3e11b62bf7fd80ba5485c2e05f/index.js#L74. `dotenv-expand` sees `$456` as a variable to look up and replaces `$456` with its value (in your case, it looks like it's replacing it with the empty string).

It looks like [`dotenv-expand` doesn't like `!`](https://github.com/motdotla/dotenv-expand/blob/de9e5cb0215495452f475f5be4dea1580b8217cd/lib/main.js#L8), so it stops there.

You can see this in action with the following `.env` file:

```dotenv
456=HI
TEST_1=123$456!@#%^&*()
```

`TEST_1` will become `123HI!@#%^&*()`.

To work around this, you can use `\` to escape `$` (based on https://github.com/motdotla/dotenv-expand/blob/master/test/.env#L7) and my tests with the following `.env` file:

```dotenv
TEST_1=123\$456!@#%^&*()
```

**Comment by neverendingqs** [comment]
This might be another reason to try to get #48 merged. This will allow users to choose to bypass the `dotenv-expand` functionality.

**Comment by nishabe** [comment]
Thank you, I have made the suggested change and this workaround is working as expected.

**Comment by colynb** [comment]
Thanks @neverendingqs !

**Comment by Arattian** [comment]
@neverendingqs, @colynb  The workaround is not working for me. 
For the input value of
`TEST="8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn\$iSRIP^9J6pzf3P4Ulfjaw"`
The output is 
`process.env.TEST="8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn^9J6pzf3P4Ulfjaw"`

It still replaces the \$iSRIP part with an empty string.

I have tried with single/double/without quotes.

Package version **3.1.0**

**Comment by neverendingqs** [comment]
FYI `serverless-dotenv-plugin@3.3.0` introduced #116, which allows you to turn off this behaviour.

**Comment by 94marianag** [comment]
@neverendingqs the workaround didn't work for me either, I'm using `serverless-dotenv-plugin@3.3.0`, where do we can turn-off that behaviour?

**Comment by neverendingqs** [comment]
Hi @94marianag,

Please see the linked pull request or the main README for details.

**Comment by 94marianag** [comment]
Thank you, it worked perfect!!
