### ISSUE TITLE
Read issues when value has '$' character

### ISSUE THREAD

**Issue by Arattian** [neverendingqs/serverless-dotenv-plugin#84]
The workaround mentioned here https://github.com/colynb/serverless-dotenv-plugin/issues/81 is not working for me. 
For the input value of
`TEST="8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn\$iSRIP^9J6pzf3P4Ulfjaw"`
The output is 
`process.env.TEST="8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn^9J6pzf3P4Ulfjaw"`

It still replaces the \$iSRIP part with an empty string.

I have tried with single/double/without quotes.

Package version **3.1.0**

_Originally posted by @Arattian in https://github.com/colynb/serverless-dotenv-plugin/issues/81#issuecomment-768254825_

**Comment by neverendingqs** [comment]
Unfortunately, I am unable to reproduce what you are seeing. This is the setup I have:

`.env`:

```
TEST_0=8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn\$iSRIP^9J6pzf3P4Ulfjaw
TEST_1="8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn\$iSRIP^9J6pzf3P4Ulfjaw"
```

`config.js`:

```js
module.exports = serverless => {
  serverless.cli.consoleLog({
    TEST_0: process.env.TEST_0,
    TEST_1: process.env.TEST_1
  });

  return {};
};
```

`serverless.yml`:

```yml
...
plugins:
  - serverless-dotenv-plugin

custom:
  configFile: ${file(./config.js)}
...
```

Output after running `sls package`:

```
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - TEST_0
Serverless:      - TEST_1
{
  TEST_0: '8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn$iSRIP^9J6pzf3P4Ulfjaw',
  TEST_1: '8k73fe1CDu4a%3v7FJR%&o61KHf@w!!3t8NJTdT%jn$iSRIP^9J6pzf3P4Ulfjaw'
}
...
```

I am at `serverless-dotenv-plugin@3.1.0` (latest).

Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates what you are seeing?

**Comment by neverendingqs** [comment]
FYI `serverless-dotenv-plugin@3.3.0` introduced #116, which allows you to turn off this behaviour.
